export const GET_JOB_POSITION = 'position/GET_JOB_POSITION';
export const GET_JOB_POSITION_SUCCESS = 'position/GET_JOB_POSITION_SUCCESS';
export const GET_JOB_POSITION_FAIL = 'position/GET_JOB_POSITION_FAIL';